version: '3'

services:

  postgres:
    container_name:  postgres-db
    image:           postgres:9.6.6
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8


  redis:
    build: 
      context: .
      dockerfile: redis.dockerfile
    restart: "always"
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdb:/var/lib/redis
    env_file: .env


  celery:
    restart: "always"
    build:
      context: .
      dockerfile: celery.dockerfile
    container_name: celery
    env_file: .env
    command: celery --app=mysite.celery:app worker -B --loglevel=INFO
    volumes:
      - .:/src
    links:
      - redis
      - postgres
    depends_on:
      - "redis"
      - "postgres"


  web:
    container_name: mysite
    build: .
    restart: "always"
    env_file: .env
    environment:
      - TIMEOUT=300
      - HTTP_PORT=8023
      - STATS_PORT=8024
    volumes:
      - .:/code
    ports:
      - "8023:8023"
    links:
      - postgres
    depends_on:
      - "postgres"
networks:
  default:
    external:
      name: nginx-proxy
